### ISSUE TITLE
Prevent Quote Marks being converted

### ISSUE THREAD

**Issue by adamwpe** [GrapesJS/components-custom-code#12]
If you type in a quote mark:

![image](https://user-images.githubusercontent.com/49768920/99883899-20754a80-2c22-11eb-9dde-a5e488aef26e.png)

When it gets converted to html, it's no longer a quote mark.

![image](https://user-images.githubusercontent.com/49768920/99883931-4ac70800-2c22-11eb-9dee-c410ad2d0469.png)

Is there a way to prevent this?

It does not happen if I rap it around with a script tag, but obviously, it won't be rendered.

I see that you can override the commandCustomCode I can override the 'handleSave' command, like so

```
'grapesjs-custom-code': {
                    commandCustomCode: {
                        handleSave: function() {
                            const { editor, target } = this;
                            const code = this.getCodeViewer().getContent();
                            console.log(code);
                            target.set(this.keyCustomCode,code);
                            editor.Modal.close();
                        }
                    }
                },
```

and the code variable is correct, but not too sure how target.set works since it looks like it is using backbone.js.

**Comment by Zunaib** [comment]
Hey did anyone resolve this ?

**Comment by kamalrohra** [comment]
Even I face the same issue

**Comment by hussein-khamis** [comment]
Has anyone found any solution?

**Comment by Zaxcoding** [comment]
Depending how you're using the editor, you can modify the response from `editor.getHtml` to unescape the single quotes. For instance:
```
const html = editor.getHtml({ cleanId: true });
const unescapedHtml = html.replace(/&#039;/g, "'");
```

@artf I think a good solution could be to include configurations for the editor to allow us to choose which of these escape sequences we want to include out of the ones in the [escape](https://github.com/artf/grapesjs/blob/f5869060521316da37032058140cb3505be9a526/src/utils/mixins.ts#L187-L195) mixin (or allow us to override this `escape` method entirely).

**Comment by artf** [comment]
This shouldn't be an issue anymore from this grapesjs release https://github.com/GrapesJS/grapesjs/releases/tag/v0.20.2

Anyway, for anybody who wants to update the escape logic, the proper way would be to update the [`textnode` component model](https://github.com/GrapesJS/grapesjs/blob/dev/src/dom_components/model/ComponentTextNode.ts) (eg. the `toHTML`/`__escapeContent` method)
