### ISSUE TITLE
CodeMirror components are not preloaded

### ISSUE THREAD

**Issue by vizardkill** [GrapesJS/components-custom-code#22]
I have reviewed the component and it seems that the configuration that is injected is not loaded
![image](https://user-images.githubusercontent.com/37307788/200358883-0688dd3e-dac9-43d2-83ba-472c65e78465.png)

For example in the case of themes, you have to copy the css from the package and add it to the project so that you can actually find it
![image](https://user-images.githubusercontent.com/37307788/200359213-4d8c67c5-5386-4a28-86c6-470a55fb4eb3.png)

Another problem that I find is that in case of editing a text component, when reopening the code, it does not preload the changes, but rather it stays with the initially injected code.

![image](https://user-images.githubusercontent.com/37307788/200360812-9bdd9ef5-52f7-43c2-9e49-2a540333b618.png)
![image](https://user-images.githubusercontent.com/37307788/200360905-0ac51bfd-7389-42fd-ad6e-ffe7352be47a.png)

In that order of ideas, how could I activate the extensions as autocomplete?

**Comment by vizardkill** [comment]
Up

**Comment by artf** [comment]
You're asking too much stuff outside of scope of this plugin. In your case it would be probably easier to create your own custom code component with all the logic you're asking
